C3DC:
  repository: CBIIT/c3dc-model
  mdf_directory: model-desc
  mdf_files:
  - c3dc-model.yml
  - c3dc-model-props.yml
  in_data_hub: false
  versions:
  - version: 1.4.0
    tag: 1.4.0
  - version: 2.0.0
    tag: 2.0.0
  - version: 2.0.1
    tag: 2.0.1
  - version: 2.1.0
    tag: 2.1.0
  - version: 3.0.0
    tag: 3.0.0
    ignore: true
  - version: 3.1.0
    tag: 3.1.0
  - version: 3.2.0
    tag: 3.2.0
  - version: 3.2.1
    tag: 3.2.1
  - version: 3.2.2
    tag: 3.2.2
  - version: 3.2.3
    tag: 3.2.3
  - version: 4.0.0
    tag: 4.0.0
  - version: 4.0.1
    tag: 4.0.1
  - version: 4.0.2
    tag: 4.0.2
  - version: 4.0.3
    tag: 4.0.3
  - version: 4.0.4
    tag: 4.0.4
  - version: 4.0.5
    tag: 4.0.5
  latest_version: 4.0.5
  latest_prerelease_commit: null
  latest_prerelease_version: null
CCDI:
  repository: CBIIT/ccdi-model
  mdf_directory: model-desc
  mdf_files:
  - ccdi-model.yml
  - ccdi-model-props.yml
  - terms.yml
  in_data_hub: true
  versions:
  - version: 1.9.1
    tag: 1.9.1
  - version: 2.0.0
    tag: 2.0.0
  - version: 2.1.0
    tag: 2.1.0
  - version: 3.0.0
    tag: 3.0.0
    ignore: true
  - version: 3.1.0
    tag: 3.1.0
  latest_version: 3.1.0
  latest_prerelease_commit: b86c081a6011e08bf419c233f352770e82fd5f22
  latest_prerelease_version: 3.1.0
CDS:
  repository: CBIIT/cds-model
  mdf_directory: model-desc
  mdf_files:
  - cds-model.yml
  - cds-model-props.yml
  in_data_hub: true
  versions:
  - version: 1.1.0
  - version: 1.3.0
  - version: 2.1.0
  - version: 3.1.2
  - version: 4.0.0
    tag: 4.0.0
  - version: 4.0.1
    tag: 4.0.1
  - version: 4.0.2
  - version: 4.0.3
    tag: 4.0.3-CDS-Release
  - version: 4.0.4
    tag: 4.0.4-CDS_Release
  - version: 5.0.1
    tag: 5.0.1-CDS_Release
  - version: 5.0.2
    tag: 5.0.2-CDS_Release
  - version: 5.0.3
    tag: 5.0.3-CDS_Release
  - version: 5.0.4
    tag: 5.0.4-CDS_Release
  - version: 6.0.0
  - version: 6.0.1
    tag: 6.0.1-CDS_Release
  - version: 6.0.2
    tag: 6.0.2-CDS_Release
  - version: 6.0.3
    tag: 6.0.3-CDS_Release
  - version: 6.0.4
    tag: 6.0.4-CDS_Release
  - version: 7.0.0
    tag: 7.0.0-GC_Release
  - version: 8.0.0
    tag: 8.0.0-GC_Release
  - version: 8.0.1
    tag: 8.0.1-GC_Release
  - version: 8.0.2
    tag: 8.0.2-GC_Release
  - version: 8.0.3
    tag: 8.0.3-GC_Release
  - version: 9.0.0
    tag: 9.0.0-GC_Release
  latest_version: 9.0.0
  latest_prerelease_commit: 1995e3e14d95a2aefa68d20fbab6dfcbefd8757a
  latest_prerelease_version: 9.0.0
CRDCSubmission:
  repository: pihltd/CRDCSearchModel
  mdf_directory: .
  mdf_files:
  - CRDC_Submission_MDF.yml
  - CRDC_Submission_MDF_Props.yml
  in_data_hub: false
  versions:
  - version: 0.2.0
  latest_version: 0.2.0
  latest_prerelease_commit: null
  latest_prerelease_version: null
CTDC:
  repository: CBIIT/ctdc-model
  mdf_directory: model-desc
  mdf_files:
  - ctdc_model_file.yaml
  - ctdc_model_properties_file.yaml
  in_data_hub: true
  versions:
  - version: 1.0.0
    tag: 1.0.0
  - version: 1.1.0
    tag: 1.1.0
  - version: 1.2.0
    tag: 1.2.0
  - version: 1.3.0
    tag: 1.3.0
  - version: 1.4.0
    tag: 1.4.0
  - version: 1.5.0
    tag: 1.5.0
  - version: 1.6.0
    tag: 1.6.0
  - version: 1.7.0
    tag: 1.7.0
  - version: 1.8.0
    tag: 1.8.0
  - version: 1.9.0
    tag: 1.9.0
  - version: 1.10.0
    tag: 1.10.0
  - version: 1.11.0
    tag: 1.11.0
  - version: 1.12.0
    tag: 1.12.0
  - version: 1.13.0
    tag: 1.13.0
  - version: 1.14.0
    tag: 1.14.0
  latest_version: 1.14.0
  latest_prerelease_commit: ce72bd1384a8cc9e5ae582b63524d9ca84fa9da2
  latest_prerelease_version: 1.6.0
GDC:
  repository: CBIIT/gdc-model
  mdf_directory: model-desc
  mdf_files:
  - gdc-model.yaml
  - gdc-model-props.yaml
  - gdc-model-terms.yaml
  in_data_hub: false
  versions:
  - version: 3.0.3
  latest_version: 3.0.3
  latest_prerelease_commit: null
  latest_prerelease_version: null
HTAN:
  repository: CBIIT/htan-model
  mdf_directory: model-desc
  mdf_files:
  - htan-model.yaml
  - htan-model-props.yaml
  - htan-model-terms.yaml
  in_data_hub: false
  versions:
  - version: 24.3.1
  latest_version: 24.3.1
  latest_prerelease_commit: null
  latest_prerelease_version: null
ICDC:
  repository: CBIIT/icdc-model-tool
  mdf_directory: model-desc
  mdf_files:
  - icdc-model.yml
  - icdc-model-props.yml
  in_data_hub: true
  versions:
  - version: 1.0.0
  - version: 2.0.0
    tag: v2.0.0
    ignore: true
  - version: 3.8.7
    tag: Tag_for_FE_v3.8.7_588
    ignore: true
  latest_version: 1.0.0
  latest_prerelease_commit: 8b815ce79f3a0d18af79fbb4cb4ed3c953f0110b
  latest_prerelease_version: 1.0.0
PDC:
  repository: CBIIT/pdc-model
  mdf_directory: model-desc
  mdf_files:
  - pdc-model.yaml
  - pdc-model-props.yaml
  - pdc-model-terms.yaml
  in_data_hub: false
  versions:
  - version: 2.0.2
  latest_version: 2.0.2
  latest_prerelease_commit: null
  latest_prerelease_version: null
mCODE:
  repository: nelsonwmoore/mcode-model
  mdf_directory: model-desc
  mdf_files:
  - mcode-model.yml
  - mcode-model-props.yml
  - mcode-model-terms.yml
  in_data_hub: false
  versions:
  - version: 3.0.0
  latest_version: 3.0.0
  latest_prerelease_commit: null
  latest_prerelease_version: null
