C3DC:
  repository: CBIIT/c3dc-model
  mdf_directory: model-desc
  mdf_files:
  - c3dc-model.yml
  - c3dc-model-props.yml
  - terms.yml
  in_data_hub: false
  versions:
  - 1.4.0
  - 2.0.0
  - 2.1.0
  latest_version: 2.1.0
CCDI:
  repository: CBIIT/ccdi-model
  mdf_directory: model-desc
  mdf_files:
  - ccdi-model.yml
  - ccdi-model-props.yml
  - terms.yml
  in_data_hub: true
  versions:
  - 1.9.1
  - 2.0.0
  - 2.1.0
  latest_version: 2.1.0
CDS:
  repository: CBIIT/cds-model
  mdf_directory: model-desc
  mdf_files:
  - cds-model.yml
  - cds-model-props.yml
  in_data_hub: true
  versions:
  - 1.1.0
  - 1.3.0
  - 2.1.0
  - 3.1.2
  - 4.0.0
  - 4.0.1
  - 4.0.2
  - 4.0.3
  - 4.0.4
  - 5.0.1
  - 5.0.2
  - 5.0.3
  - 5.0.4
  - 6.0.0
  - 6.0.1
  latest_version: 6.0.1
CRDCSubmission:
  repository: pihltd/CRDCSearchModel
  mdf_directory: .
  mdf_files:
  - CRDC_Submission_MDF.yml
  - CRDC_Submission_MDF_Props.yml
  in_data_hub: false
  versions:
  - 0.2.0
  latest_version: 0.2.0
CTDC:
  repository: CBIIT/ctdc-model
  mdf_directory: model-desc
  mdf_files:
  - ctdc_model_file.yaml
  - ctdc_model_properties_file.yaml
  in_data_hub: true
  versions:
  - 1.0.0
  - 1.1.0
  - 1.2.0
  latest_version: 1.2.0
GDC:
  repository: CBIIT/gdc-model
  mdf_directory: model-desc
  mdf_files:
  - gdc-model.yaml
  - gdc-model-props.yaml
  - gdc-model-terms.yaml
  in_data_hub: false
  versions:
  - 3.0.3
  latest_version: 3.0.3
HTAN:
  repository: CBIIT/htan-model
  mdf_directory: model-desc
  mdf_files:
  - htan-model.yaml
  - htan-model-props.yaml
  - htan-model-terms.yaml
  in_data_hub: false
  versions:
  - 24.3.1
  latest_version: 24.3.1
ICDC:
  repository: CBIIT/icdc-model-tool
  mdf_directory: model-desc
  mdf_files:
  - icdc-model.yaml
  - icdc-model-props.yaml
  in_data_hub: true
  versions:
  - 1.0.0
  - 2.0.0
  - 3.8.7
  latest_version: 3.8.7
PDC:
  repository: CBIIT/pdc-model
  mdf_directory: model-desc
  mdf_files:
  - pdc-model.yaml
  - pdc-model-props.yaml
  - pdc-model-terms.yaml
  in_data_hub: false
  versions:
  - 2.0.2
  latest_version: 2.0.2
mCODE:
  repository: nelsonwmoore/mcode-model
  mdf_directory: model-desc
  mdf_files:
  - mcode-model.yml
  - mcode-model-props.yml
  - mcode-model-terms.yml
  in_data_hub: false
  versions:
  - 3.0.0
  latest_version: 3.0.0
