name: ci-cd
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:      
      - name: Check-out repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - name: Install Python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86
        with:
          version: "0.5.10"

      - name: Install dependencies and project
        run: |
          uv pip install --system -e .
          uv sync --all-extras --dev

      - name: Test with pytest
        run: |
          source .venv/bin/activate
          pytest --cov=bento_mdb_updates --cov-report=xml
