name: liquibase-update

on:
  push:
    branches: [ main ]
    paths:
      - 'data/output/model_changelogs/**/*.xml'
      - 'data/output/term_changelogs/**/*.xml'
  pull_request:
    branches: [ main ]
    paths:
      - 'data/output/model_changelogs/**/*.xml'
      - 'data/output/term_changelogs/**/*.xml'
  workflow_dispatch:
    inputs:
      changelog_file:
        description: "Path to changelog file to update"
        required: true

jobs:
  liquibase-update:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.10"

      - name: Install dependencies
        run: |
          uv sync --all-extras --dev

      - name: Install project
        run: |
          uv pip install .

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@039afcd1024c210363c9d3fc8fd07e1f3fcf2867
        with:
          files: |
            data/output/model_changelogs/**/*.xml
            data/output/term_changelogs/**/*.xml

      - name: Liquibase update
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Processing $file"
            prefect deployment run liquibase-update \
              --params "{\"mdb_uri\": \"${{ secrets.NEO4J_MDB_URI }}\", \"mdb_user\": \"${{ secrets.NEO4J_MDB_USER }}\", \"mdb_pass\": \"${{ secrets.NEO4J_MDB_PASS }}\", \"changelog_file\": \"$file\"}"
          done
    