name: Generate and Commit Term Update Changelog

on:
  schedule:
    - cron: "0 0 * * 0" # runs every Sunday at midnight UTC
  workflow_dispatch:
    inputs:
      mdb_uri:
        description: "URI for Neo4j MDB instance"
        required: false
        default: ""
      mdb_user:
        description: "Username for Neo4j MDB"
        required: false
        default: ""
      mdb_pass:
        description: "Password for Neo4j MDB"
        required: false
        default: ""
      author:
        description: "Author name for changes"
        required: false
        default: "GitHub Actions"
      commit_sha:
        description: "Commit SHA for reference"
        required: false
        default: ""

jobs:
  update-mdb-terms:
    runs-on: ubuntu-latest
    outputs:
      affected_models: $ {{ steps.update-terms.outputs.affected_models }}
      changelog_files: $ {{ steps.update-terms.outputs.changelog_files }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.10"

      - name: Install dependencies and project
        run: |
          uv pip install --system -e .
          uv sync --all-extras --dev
      
      - name: Update terms
        id: update-terms
        run: |
          RESULT=$(update_terms \
            --mdb_uri="${{ github.event.inputs.mdb_uri || secrets.NEO4J_MDB_URI }}" \
            --mdb_user="${{ github.event.inputs.mdb_user || secrets.NEO4J_MDB_USER }}" \
            --mdb_pass="${{ github.event.inputs.mdb_pass || secrets.NEO4J_MDB_PASS }}" \
            --author="${{ github.event.inputs.author || 'GitHub Actions Bot' }}" \
            --_commit="${{ github.event.inputs.commit_sha || github.sha }}")

          AFFECTED_MODELS=$(echo $RESULT | jq -r '.affected_models')
          CHANGELOG_FILES=$(echo $RESULT | jq -r '.changelog_files')

          echo "affected_models=$AFFECTED_MODELS" >> $GITHUB_OUTPUT
          echo "changelog_files=$CHANGELOG_FILES" >> $GITHUB_OUTPUT

          echo "Affected models: $AFFECTED_MODELS"
          echo "Changelog files: $CHANGELOG_FILES"

      - name: Commit Generated Changelog
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

          if [ -d "data/output/term_changelogs/" ]; then
            git add data/output/term_changelogs/
          fi
          
          if [ -d "data/output/mdb_cdes/" ]; then
            git add data/output/mdb_cdes/
          fi
          
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update term changelogs and MDB CDEs"
            git push
          else
            echo "No changes to commit"
          fi

  liquibase-update:
    needs: [update-mdb-terms]
    if: needs.update-mdb-terms.outputs.affected_models != '[]' && needs.update-mdb-terms.outputs.changelog_files != '[]'
    uses: ./.github/workflows/liquibase_update.yml
    secrets: inherit
    with:
      changelog_files: ${{ needs.update-mdb-terms.outputs.changelog_files }}
      affected_models: ${{ needs.update-mdb-terms.outputs.affected_models }}